apiVersion: v1
kind: Pod
metadata: 
  name: webserver
  labels: 
    app: myapp
spec:
  containers: 
    - name: firstcontainer
      image: coolgourav147/nginx-custom
      imagePullPolicy: Never
      resources:
        requests:
          memory: 100Mi
          cpu: 0.1
        limits:
          cpu: 0.5
          memory: 150Mi
