apiVersion: v1

kind: ReplicationController

metadata:
  name: firstrc
  labels:
    name: firstrc

spec:
  replicas: 2
  selector:
    app: myapp
  template:
    metadata:
      name: pod1
      labels:
        app: myapp
    spec: 
      containers:
        - image: coolgourav147/nginx-custom
          name: firstcontainer
  
