apiVersion: v1
kind: Pod
metadata: 
  name: firstpod
  labels: 
    env: prod

spec:
  containers: 
    - name: firstcontainer
      image: coolgourav147/nginx-custom
      env: 
        - name: myname
          value: mihir
      args: ["sleep", "3600"]
    - name: secondcontainer
      image: coolgourav147/nginx-custom
  initContainers: 
    - name: initcontainer
      image: coolgourav147/nginx-custom
      env:
        - name: myname
          value: mihir
      args: ["sleep", "30"]
