apiVersion: v1
kind: Pod
metadata: 
  name: webserver
  labels: 
    app: myapp1
spec:
  containers: 
    - name: firstcontainer
      image: coolgourav147/nginx-custom
      imagePullPolicy: Never
      resources:
        requests:
          memory: 1Mi
        limits:
          memory: 200Mi
