apiVersion: v1
kind: Pod
metadata: 
  name: pod1
  labels: 
    app: myapp
    type: fontend

spec:
  containers: 
    - name: firstcontainer
      image: coolgourav147/nginx-custom
#      envFrom:
#        - configMapRef:
#            name: cm3
      volumeMounts:
        - name: test
          mountPath: "/config"
          readOnly: true

  volumes:
    - name: test
      configMap:
        name: cm3
#      env:
#       - name: variablefromcm
#         valueFrom:
#           configMapKeyRef:
#             key: name
#             name: cm3
