name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  pull-nginx:
    runs-on: self-hosted
    container:
      image: quay.io/podman/stable
      options: --privileged
    steps:
      - name: Pull Nginx with Podman
        run: |
          podman pull docker.io/library/nginx:latest
