name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: arc-runner-set

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker pull mihir.harbor.com/inventyv/nginx-custom
