apiVersion: v1
kind: Pod
metadata: 
  name: pod1
  labels: 
    app: myapp
    type: fontend

spec:
  containers: 
    - name: firstcontainer
      image: coolgourav147/nginx-custom
      volumeMounts:
        - mountPath: /secrets
          name: testsec

  volumes:
    - name: testsec
      secret:
        secretName: fromenvfile
      
#      envFrom:
#        - secretRef:
#            name: fromenvfile
#      env:
#        - name: myvariable
#          valueFrom:
#            secretKeyRef:
#              key: name
#              name: fromenvfile 
